* Introduction
  
If you use GNU/Emacs  maybe you have known "Anything"
maybe not , 
you can visit "Anything" on [[http://www.emacswiki.org/emacs/Anything%20][Emacswiki]]
and see what "Anything" it is .
and this isn't anything.el ,it 's anything.ahk.
if you think anything.ahk is great ,
and have written an anything-source for it ,you can post it here .
  
there is a screencast here :
+ http://www.screenr.com/xxss
+ http://www.screenr.com/vp8s (new one )
+ http://www.screenr.com/BH7s and another one show anything-favorite-directories.ahk
+ http://www.screenr.com/MyHs and another show anything-window-switch.ahk

you can also download these videos
+ http://screencast-repos.googlecode.com/files/anything-expl-run.mp4
+ http://screencast-repos.googlecode.com/files/anything.ahk-anything-explorer-history.mp4
+ http://screencast-repos.googlecode.com/files/anything-window-switch.mp4
+ http://screencast-repos.googlecode.com/files/anything-fav-dir.mp4

and source code is host on
+ https://github.com/jixiuf/my_autohotkey_scripts/tree/master/ahk_scripts

you can follow these links ,and save them on you disk .
+ https://github.com/jixiuf/my_autohotkey_scripts/raw/master/ahk_scripts/anything.ahk
+ https://github.com/jixiuf/my_autohotkey_scripts/raw/master/ahk_scripts/anything-explorer-history.ahk
+ https://github.com/jixiuf/my_autohotkey_scripts/raw/master/ahk_scripts/anything-favorite-directories.ahk
+ https://github.com/jixiuf/my_autohotkey_scripts/raw/master/ahk_scripts/anything-run.ahk
+ https://github.com/jixiuf/my_autohotkey_scripts/raw/master/ahk_scripts/anything-window-switch.ahk
+ https://github.com/jixiuf/my_autohotkey_scripts/raw/master/ahk_scripts/anything-config.ahk

* Active <Anything>
  to active anything.ahk , press F3 , or Windows+r , or Alt+TAB
  see  [[https://github.com/jixiuf/my_autohotkey_scripts/raw/master/ahk_scripts/anything-config.ahk][anything-config.ahk]]  for detail 
* keybindings when <Anything> is activated 
  you can input search string just like google to narrow the candidates
** keybindings for select candiates
| Down or Ctrl+n          | select next candidate                                                                     |
| Up or Ctrl+p            | select previous candidate                                                                 |
| Ctrl+o                  | will select next source ,that means ,all candidate from first source will be send to last |
| pageUp ,Ctrl-r ,Alt-v   | pageup                                                                                    |
| pageDn ,Ctrl-v          | pageDn                                                                                    |

** keybindings for execute actions

| <Click>and  <Enter>  | to execute the default action with the selected candiate as parameter                                                                             |
| <Ctrl-j>             | to execute the second action with the selected candidate as parameter                                                                             |
| <Ctrl-m>             | to execute the third action with the selected candidate as parameter                                                                              |
| <Ctrl-z> <Alt-Enter> | do the same to Enter ,but doesn't quit "Anything"                                                                                                 |
| <Alt-j>              | do the same to Ctrl-j ,but doesn't quit "Anything"                                                                                                |
| <Alt-m>              | do the same to Ctrl-m ,but doesn't quit "Anything"                                                                                                |
| <tab>                | will list all available actions , and you can select one to execute .                                                                             |
| <Ctrl-L>             | will ignore all the candidates ,and treate the search string as candidate , and list all available "action" to execute on the special "candidate" |
| <Ctrl-i>             | do something similar to <Ctrl-l> ,but don't list all available "action" ,just execute the "action" special by "property": no_candidate_action     |
| <Esc> and <Ctrl-g>   | quit Anything                                                                                                                                     |

** keybindings for edit
| Ctrl-u               | delete all search string |
| backspace and Ctrl-h | back delete a char       |
| Ctrl-y               | paste                    |

* anything-source I have written
Now I have wrote 4 <anything-source> for anything.ahk
  +  anything-explorer-history.ahk ,
  +  anything-favorite-directories.ahk,
  +  anything-run.ahk (a replacement of Windows+r)
  +  anything-window-switch.ahk (a replacement of Alt-Tab)

**  anything-explorer-history.ahk
   when you visit  directory (double click on a directory,up or back ) in
   explorer.exe ,it can remember directories 
   you have visited ,then you can press  <F3> to active "Anything"
   list all directory history ,you can revisit it easyly.
   how to use anything-explorer-history.ahk
    
***    if you only have one anything-source :
       anything_explorer_history_source  (defined in  anything-explorer-history.ahk)
       you can use it like this :
   #+begin_src c
       #include anything.ahk
       #include anything-explorer-history.ahk
       f3::anything(anything_explorer_history_source)
   #+end_src
       
***      if you also have other anything-sources ,
        default  : it is included in anything-config.ahk
        you just need add 
            anything_explorer_history_source
        to the sources
       for example :
#+begin_src c
       f3::
       sources:=Array()
       sources.insert(anything_explorer_history_source)
       sources.insert(anything_favorite_directories_source)
       sources.insert(anything_cmd_source)
       anything_multiple_sources(sources)
       return
#+end_src       
*** actions for anything-explorer-history.ahk
    #+begin_src c
   anything_explorer_history_source["action"]:=Array("visit_directory","delete_from_directory_history" ,"delete_all_directory_history")
    #+end_src
| actions                       | description                                     | key binding         |
|-------------------------------+-------------------------------------------------+---------------------|
| visit_directory               | visit selected directory                        | <Click>and  <Enter> |
| delete_from_directory_history | delete select directory from  directory history | <Ctrl-j>            |
| delete_all_directory_history  | add a new directory to  directory history       | <Ctrl-m>            |
| list all actions              |                                                 | <Ctrl-L>            |
   
**  anything-favorite-directories.ahk  do something like anything-explorer-history.ahk
   add your favorite directories ,and visit it using "Anything".
   about how to use it .see comments in anything-favorite-directories.ahk
   if you use anything-favorites-directory as the only source for anything.ahk
   you just need to bind it to a key like this :
    #+begin_src c
      #include anything.ahk
      #include anything-favorites-directory.ahk
      f1::anything(anything_favorite_directories_source)
    #+end_src

   if you also use other sources ,just need add "anything_favorite_directories_source" to 
   the array of sources for anything_multiple_sources(sources)
   default have added to  anything-config.ahk 

***    how to add a new Folder to your favorite-directories
   first activate "Anything" and Press <Ctrl-L> list all available actions
   select "call action: Favdirs.anything_favorite_directories_add "
   about what the meaning of <Ctrl-L>
   anything_favorite_directories_source have three actions
   anything_favorite_directories_source["action"]:=Array("anything_favorite_directories_visit","anything_favorite_directories_delete","anything_favorite_directories_add")
*** actions for   anything-favorite-directories.ahk 
| actions                              | description                                       | key binding         |
|--------------------------------------+---------------------------------------------------+---------------------|
| anything_favorite_directories_visit  | visit selected directory                          | <Click>and  <Enter> |
| anything_favorite_directories_delete | delete select directory from favorite directories | <Ctrl-j>            |
| anything_favorite_directories_add    | add a new directory to favorite directories       | <Ctrl-m>            |
| list all actions                     |                                                   | <Ctrl-L>            |

***    then you can use "Anything" selected one of your favorite directory 
   + it will visit it in current Explorer.exe (if current activated window is Explorer.exe)
   + it will visit it in current cmd.exe (if current activated window is cmd.exe)
   + it will visit it in current msys.bat (if current activated window is msys.bat)


** anything-run.ahk is a replacement of <Win-r>
   it could remember old  command too. when you press <F3>
   about how to use it .see comments in anything-run.ahk
** anything-window-switch.ahk is a replacement of Alt-Tab   
   
** you just need download:
   + anything.ahk
   + anything-explorer-history.ahk
   + anything-favorite-directories.ahk
   + anything-run.ahk
   + anything-window-switch.ahk
   + anything-config.ahk
   + and run anything-config.ahk
 
* how to  write an anything-source
  an anything-source is an Object with some defined properties
  now it support 5 anything-source-properties :
  + name
  + action
  + candidate
  + icon
  + anything-execute-action-at-once-if-one
  for example:
  #+begin_src c
        my_source:=Object()
  #+end_src
** 1 <name>  (needed)
   <name> is a string ,it is just a name of this anything-source
   #+begin_src c
        my_source["name"]:="my_source_name"
   #+end_src
** 2 <candidate>  (needed)
   <candidate> is an array of available candidates ,or a function name(string)
   without parameter which return an array .
   each element of the array can be :
*** a string
    this string will be displayed on listview , so that you can select one
    of the candidates ,and execute action on your selected candidate.
   for example:
   #+begin_src c
            my_candidates:=Array("red","green")
   #+end_src
      or
      #+begin_src c
            my_candidates_fun()
            {
                return Array("red","green")
            }
            my_candiates:="my_candidates_fun"
           my_source["candidate"]:=my_candidates
      #+end_src
*** an array
    the first element of this array must be a string ,the string will be
    displayed on listview ,and you can selected one of the candidates ,and
    execute action on your selected candidate.
    other element of this array can be anything , you can store useful info.
    there. and when you execute action on your selected candidate,this will
    be the parameter . see <action>
      for example:
      #+begin_src c
            my_candidates:=Array(
                      Array("red","useful info ,string ,object or anything"),
                      Array("green","useful info ,string ,object or anything")
                      )
      #+end_src

** 3 <action>  (needed)
   <action> is a function name(string) or a list of function name (array).
   and those functions must have one parameter. actually the parameter is
   the selected <candidate> .
   #+begin_src c
         my_action:="my_action_fun"
                  my_action_fun(candidate)
                {
                  MsgBox , %candidate%
                }
   #+end_src
      or
      #+begin_src c
        my_action:=Array("my_action_fun","my_action_fun2")
                  my_action_fun(candidate)
                {
                  MsgBox , %candidate%
                }
                  my_action_fun2(candidate)
                {
                  MsgBox , %candidate%
                }

      my_source["action"]:=my_action
      #+end_src
** 4 <icon> (optional)
    <icon> is a function(string) which return a ImageList.
    this property is optional .if this property isn't empty
    <Anything> will display icon before each candidates.
    #+begin_src c
     icon_fun()
     {
         ImageListID := IL_Create(10)  ; Create an ImageList to hold 10 small icons.
         Loop 10  ; Load the ImageList with a series of icons from the DLL.
         IL_Add(ImageListID, "shell32.dll", A_Index)
         return ImageListID
     }
    my_icon :="icon_fun"
    my_source["icon"]:=my_icon
    #+end_src

** 5 <anything-execute-action-at-once-if-one> (optional)
    if it has value
  for example
  #+begin_src c
          my_source["anything-execute-action-at-once-if-one"]:="yes"
  #+end_src
then if only one candidate left on the listview it will execute the
    default action with the candidate
** 6 call anything
   #+begin_src c
    anything(my_source)
   #+end_src
